// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAPIAssginment.Models.Data;

#nullable disable

namespace WebAPIAssginment.Migrations
{
    [DbContext(typeof(WebAPIContext))]
    [Migration("20250426120829_AddAlltablesWithSeeds")]
    partial class AddAlltablesWithSeeds
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebAPIAssginment.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Mobiles"
                        },
                        new
                        {
                            Id = 2,
                            Name = "TVs"
                        });
                });

            modelBuilder.Entity("WebAPIAssginment.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Good Phone",
                            Name = "Iphone 11",
                            Price = 1000.0
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "Good Phone",
                            Name = "Galaxy S22 Ultra",
                            Price = 9999.0
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            Description = "Good Phone",
                            Name = "LG TV",
                            Price = 1000.0
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Description = "Good Phone",
                            Name = "Samsung TV",
                            Price = 1000.0
                        });
                });

            modelBuilder.Entity("WebAPIAssginment.Models.Product", b =>
                {
                    b.HasOne("WebAPIAssginment.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("WebAPIAssginment.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
